### ISSUE TITLE
Move settings out of user settings

### ISSUE THREAD

**Issue by adzenith** [SublimeText/Origami#101]
They should be in Origami settings. This would solve e.g. #81.

**Comment by gerardroche** [comment]
I don't agree with this. I actually think plugins should not have their own individual settings files. I don't know why or when the practice of named settings files started. It causes all kinds of problems that are not an issue if you use user settings.

For example, when you put settings in a named file e.g. Origami.sublime-settings, it's now your responsibility to load the settings. You now also need to implement, from scratch, project specific settings. The settings are also not available to various elements like key bindings.

For example, consider the following key bindings definition:

```
{
    { 
        "keys": ["ctrl+shift+t"], 
        "command": "phpunit_run_all_tests", 
        "context": [{ "key": "setting.origami.keymaps" }] 
    }
}
```

And imagine two different approaches to settings:

* A named settings file: `Packages/Origami/Origami.sublime-settings`
* A user settings file: `Packages/Origami/Preferences.sublime-settings`

Both contain the same thing:

```
{
    "origami.keymaps": true
}
```

The `Preferences.sublime-settings` already works out of the box. Not only does it work out of the box, you can also have project specific settings for free!

`Project > Edit Project`

```
{
    "settings": {
        "origami.keymaps": false   
     }
}
```

You want to access the setting in code?

In a text command:

```
self.view.settings().get('origami.keymaps'))
```

A generic function:

```
def get_setting(key, default = None):
    view = sublime.active_window().active_view()
    if view: 
        return view.settings().get(key, default)
    else:
       return default
```

The limitations of the ST API are not solved by named settings files. The argument that settings are harder to maintain in one file? I like using the convention of prefixing my plugin settings with `plugin_name.` so all those settings in a sorted `Preferences.sublime-settings` are grouped together, which I think is easier to maintain.

But perhaps I'm missing something, I just don't see the value of named settings files.

**Comment by FichteFoll** [comment]
Imo named settings file are valuable for a) packages with huge configuration options rivaling St's default preferences file and b) strictly global settings. Other than that, using ST's default configuration infrastructure is advantageous from a user and developer perspective because it provides more configurability for less work.

**Comment by gerardroche** [comment]
On a) what do you consider huge? For example, as a metric of what percentage of packages would you would consider to have huge enough configurations?

b) Strictly global settings? Like [how the `ignored_packages` setting works](https://stackoverflow.com/questions/39806491/how-to-enable-disable-certain-snippets-for-specific-projects-in-sublime-text/39808614#comment66921048_39809918)? It makes sense that `ignored_packages` is global only. Though I think the term "global" in this context is not fully clear to most package authors. I didn't think of these type of settings. On face value, it seems like this is precisely what named settings files are useful for. I still think that huge configurations files, no matter how huge, are no more useful as named settings files as they are non-named. Having a clear distinction between global (named) and non-global (non-named) seems very useful.

**Comment by FichteFoll** [comment]
a) mostly some highly configurable packages and multi-language or general purpose packages like BracketHighlighter or SublimeLinter. Their configuration files can quickly grow over 100 lines.
Furthermore, the automatic sorting of settings caused by re-dumping the JSON, which also removes comments, can cause quite some confusion with regard to default settings being lost between multiple package-specific settings. This is really my main concern with a).

b) Yes, imo the core "global" settings like `theme` should be in a separate 'global' settings file, which would clearly indicate their *global* nature and make it clear that project overrides are not possible.

**Comment by adzenith** [comment]
Fixed in https://github.com/SublimeText/Origami/commit/c600c07286611953797b082fc039eac0c99c79bc
