### ISSUE TITLE
origami_auto_zoom_on_focus & origami_auto_close_empty_panes not working

### ISSUE THREAD

**Issue by Xtremefaith** [SublimeText/Origami#107]
I cannot for the life of me get either `origami_auto_zoom_on_focus` or `origami_auto_close_empty_panes` to work. I'm not sure if my expectations are wrong or if some how my understanding of how to enable them is off, but so far I'm having no luck.

I using Sublime Text 3, Build 3114 (current), Windows 7. and here are my current origami settings file:

**Origami.sublime-settings**
```
{
	"origami_auto_zoom_on_focus": true,
	"origami_auto_close_empty_panes": true
}
```

also tried setting `origami_auto_zoom_on_focus` to 0.75. And also tried restarting Sublime afterwards. I can manually zoom an active panel just fine and I assumed auto zoom would just do the same thing when click on the pane but nothing happens. Likewise, when I close the last file in a panel I thought it would remove the panel but it doesn't

**Comment by adzenith** [comment]
You have to put it in your user settings... Origami was written in the early days of Sublime Text, and I don't even know if we used to have these fancy plugin settings. Now everybody has the options in their user settings already. At some point it needs to be changed so that it'll read user settings as well as its own settings.
