### ISSUE TITLE
Make it easier to learn hotkeys

### ISSUE THREAD

**Issue by septagram** [SublimeText/Origami#120]
I keep trying to remember the Origami hotkeys, but all I manage to remember is `Ctrl+K`.

It would be great if, when I press `Ctrl+K` something would happen that will remind me of the hotkeys, something like a message in the status bar:

> "Press [Direction] to move to another pane, Ctrl+[Direction] to create a pane, Ctrl+Shift+[Direction] to destroy a pane"

Or even shorter:

> "Move to: [Dir], Create: Ctrl+[Dir], Destroy: Ctrl+Shift+[Dir], Move file: Shift+[Dir]" (and other hotkeys)

**Comment by Schoema3** [comment]
Maybe it would help to display the shortcuts under:  

> View- > Origami -> ...

**Comment by septagram** [comment]
That's still a lot of key presses to open... And it ends up with just picking the one from the menu, and never using the actual shortcuts.

**Comment by adzenith** [comment]
The shortcuts are displayed under the view menu now.
It's hard to print something out when you hit ctrl+k, because origami doesn't get activated until the second keypress (Sublime Text does some magic for you there). ctrl+k is also used to hide other commands as well. I think I'll close for now because they're in the view menu.
