### ISSUE TITLE
automatic switch to new pane

### ISSUE THREAD

**Issue by niamiot** [SublimeText/Origami#61]
Hi, 

Would it be possible to add an option to automatically switch to the newly created pane  ? (create + travel in one command)

It would reduce the workflow from :
ctrl+K / ctrl+-> , ctrl+K /->
to 
ctrl+K / ctrl+(alt?)+->

Maybe it already exists ?

Thank

**Comment by adzenith** [comment]
That seems like a pretty good idea. Origami has functions to ask about the closest pane in a direction, so you could use that (and the direction argument) instead of the group number.

Incidentally, I believe that the way group numbers work is that they're just an index into an array of coordinates that define panes. The group numbers don't have much to do with the order of panes on screen. Because of this, the newly created pane's group number is not necessarily close to the current pane's.

**Comment by adzenith** [comment]
Closed by #79.
